### ISSUE TITLE
第二个数据预处理跑不了

### ISSUE THREAD

**Issue by 718155407** [cherubicXN/afm_cvpr2019#1]
York Urban的数据格式编排，有些歧义，整理过后还是跑不了预处理，望您能给终于帮助，万分感谢

**Comment by cherubicXN** [comment]
You need to use matlab to read the YorkUrban dataset and write the images and line segments into "filename_rgb.png" and "filename.mat". The line segments in the mat file should be saved with the variable 'line'.  In our evaluation, we only use the test data (51 images). You can read the guideline of YorkUrban dataset for the format.

**Comment by 718155407** [comment]
Thank u very much,I will try it again。

**Comment by BrianPugh** [comment]
Here's a MATLAB script I wrote to do the preprocessing. Since YorkUrban is such a small dataset, it might be worthwhile just to reupload it in the preprocessed format.

This is to be ran in the `york_raw` directory with the YorkUrbanDB unzipped to that directory.
```
york_urban_db_path = 'YorkUrbanDB';
load(fullfile(york_urban_db_path, 'Manhattan_Image_DB_Names.mat'));
load(fullfile(york_urban_db_path,'ECCV_TrainingAndTestImageNumbers.mat'));

n_exemplars = length(Manhattan_Image_DB_Names);
for i = 1:n_exemplars
    name = Manhattan_Image_DB_Names{i}(1:end-1);
    fprintf('Processing %d/%d\r', i, n_exemplars);
    
    %% Image Ontology Preprocess
    input_im_path = fullfile(york_urban_db_path, name, [name, '.jpg']);
    output_im_path = [name, '_rgb.png'];
    
    im = imread(input_im_path);
    imwrite(im, output_im_path);
    
    %% Line Segment Ontology Preprocess
    input_contents_path = fullfile(york_urban_db_path, name, [name, 'LinesAndVP.mat']);
    output_contents_path = [name, '.mat'];
    
    contents = load(input_contents_path);
    line = contents.lines;
    
    save(output_contents_path, 'line');
end
```

**Comment by MichealSJTU** [comment]
请问你第一个数据集下载好了吗？可否分享一下？谢谢。

**Comment by dhuznn** [comment]
请问你第一个数据集下载好了吗？可否分享一下？谢谢。
