### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by tianyu0523** [cherubicXN/afm_cvpr2019#10]
When I run 'make', I met this issue. Could you please help me address it?
![image](https://user-images.githubusercontent.com/25603473/59554430-57feb280-8fab-11e9-99cf-d3d0c3f55645.png)

**Comment by GuangZhaoZhou** [comment]
it will disappear if you install cuda and cudnn.good lucky

**Comment by Jack-bo1220** [comment]
I have the same issue, could you tell me how you solved it? 
I'm sure I have cuda available
@tianyu0523 @GuangZhaoZhou
