### ISSUE TITLE
ImportError: No module named 'squeeze.squeeze'

### ISSUE THREAD

**Issue by sutao29** [cherubicXN/afm_cvpr2019#14]
![image](https://user-images.githubusercontent.com/52815880/63493741-c9e50200-c4ee-11e9-9908-ec51669c2465.png)

**Comment by WujiangXu** [comment]
Did you solve this problem?I met the same question as you

**Comment by cherubicXN** [comment]
Did you check if there is a file named "squeeze.cpython-****.so"?

**Comment by whykun** [comment]
I have the same problem

**Comment by whykun** [comment]
try to change the path of 'squeeze', like it "<AFM_root>/squeeze"

**Comment by 3D-A** [comment]
I sloved it by `git clean -xdf` and   `make` again

**Comment by cherubicXN** [comment]
> I sloved it by `git clean -xdf` and `make` again

That's great! Thanks.
