### ISSUE TITLE
How can I evaluate a photo not in the dataset

### ISSUE THREAD

**Issue by WujiangXu** [cherubicXN/afm_cvpr2019#16]
I see that test a photo use the function AFM which need the information about some known lines.But I want to test the photo which I dont have the line information.

**Comment by MuhammadShehryarKhan** [comment]
@cupcakefromchina how were you able to solve the problem if i may ask?

**Comment by WujiangXu** [comment]
> @cupcakefromchina how were you able to solve the problem if i may ask?

No,I can't fine one function.You can see another issue.

**Comment by JanineCHEN** [comment]
Hi, having the same question here. Is it possible to direct test the model on an image in the wild without any line information? Thank you.
