### ISSUE TITLE
no module named squeeze

### ISSUE THREAD

**Issue by WujiangXu** [cherubicXN/afm_cvpr2019#17]
I run the code and get this error.
`from squeeze.squeeze import region_grow
ImportError: No module named 'squeeze'`
I saw in the squeeze folder don't have any squeeze.py

Can you give me some help?
Thank u for u reply.

**Comment by cherubicXN** [comment]
Did you compile the cxx files?

**Comment by WujiangXu** [comment]
> Did you compile the cxx files?

I have compiled in the lib folder.Just like in the install.md and get the information like another issue.

**Comment by cherubicXN** [comment]
If the squeeze.*.so file has been generated, can you try to import it in the folder of the .so file?

**Comment by WujiangXu** [comment]
> If the squeeze.*.so file has been generated, can you try to import it in the folder of the .so file?

Did it mean that I need to `cdll.LoadLibrary`  to import .so file in the squeeze_to_lsg.py.Because it cause the error in this file.
those are error function name
lsgenerator --->  region_grow

**Comment by WujiangXu** [comment]
Sorry to  interrupt you.I also have anothor question.I test just one photo which is not in the dataset you provide.Do I need to do some change to the input.I saw the model that need (64,3,3,3).I can't understand this.Which size I need to resize the photo.

**Comment by cherubicXN** [comment]
> Sorry to interrupt you.I also have anothor question.I test just one photo which is not in the dataset you provide.Do I need to do some change to the input.I saw the model that need (64,3,3,3).I can't understand this.Which size I need to resize the photo.

The input image should have 3 channels and you need to resize it into 320x320 if you train the model with 320x320 training samples.

**Comment by WujiangXu** [comment]
> > Sorry to interrupt you.I also have anothor question.I test just one photo which is not in the dataset you provide.Do I need to do some change to the input.I saw the model that need (64,3,3,3).I can't understand this.Which size I need to resize the photo.
> 
> The input image should have 3 channels and you need to resize it into 320x320 if you train the model with 320x320 training samples.

If I use the model which you provided,I also need to change the photo to 320?I use the unet.

**Comment by cherubicXN** [comment]
> h

Yes

**Comment by WujiangXu** [comment]
> > h
> 
> Yes

In the squeeze_to_lsg.py, line 3 ,you import the 
`from squeeze.squeeze import region_grow`,
and it will be a error. So I substitute it,just like it.
`lib1 = cdll.LoadLibrary('/home/xyf/dataset/rotate/afm_cvpr2019-master/afm_cvpr2019-master/lib/squeeze/squeeze.cpython-35m-x86_64-linux-gnu.so')
    
    rects = lib1.region_grow(xx, yy, theta, np.array([H, W], dtype=np.int32))
`
I use the cdll to load the .so file,but it make other error.
`AttributeError: squeeze.cpython-35m-x86_64-linux-gnu.so: undefined symbol: region_grow`

**Comment by WujiangXu** [comment]
I can't use the function in the squeeze_to_lsg.py. It called region_grow.Is it important to the information for the line.

**Comment by preston2006** [comment]
from .squeeze.squeeze import region_grow
